///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AuthModelDataRoleFeaturePermissionsFeature {
/*
{
  "id": "8c43b43c-65a7-4598-89eb-1e4f0d983bd8",
  "name": "EMPLOYEE_MANAGEMENT",
  "isActive": true,
  "createdAt": "2025-04-29T13:26:51.120Z",
  "updatedAt": "2025-04-29T13:26:51.120Z",
  "deletedAt": null
}
*/

  String? id;
  String? name;
  bool? isActive;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  AuthModelDataRoleFeaturePermissionsFeature({
    this.id,
    this.name,
    this.isActive,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  AuthModelDataRoleFeaturePermissionsFeature.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    isActive = json['isActive'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    deletedAt = json['deletedAt']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['isActive'] = isActive;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['deletedAt'] = deletedAt;
    return data;
  }
}

class AuthModelDataRoleFeaturePermissions {
/*
{
  "id": "245f41aa-827d-4626-8bc6-1fbb3c7fde3d",
  "feature": {
    "id": "8c43b43c-65a7-4598-89eb-1e4f0d983bd8",
    "name": "EMPLOYEE_MANAGEMENT",
    "isActive": true,
    "createdAt": "2025-04-29T13:26:51.120Z",
    "updatedAt": "2025-04-29T13:26:51.120Z",
    "deletedAt": null
  },
  "create": true,
  "view": true,
  "update": true,
  "delete": true,
  "createdAt": "2025-04-29T13:26:50.797Z",
  "updatedAt": "2025-04-29T13:26:50.797Z",
  "deletedAt": null
}
*/

  String? id;
  AuthModelDataRoleFeaturePermissionsFeature? feature;
  bool? create;
  bool? view;
  bool? update;
  bool? delete;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  AuthModelDataRoleFeaturePermissions({
    this.id,
    this.feature,
    this.create,
    this.view,
    this.update,
    this.delete,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  AuthModelDataRoleFeaturePermissions.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    feature = (json['feature'] != null)
        ? AuthModelDataRoleFeaturePermissionsFeature.fromJson(json['feature'])
        : null;
    create = json['create'];
    view = json['view'];
    update = json['update'];
    delete = json['delete'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    deletedAt = json['deletedAt']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (feature != null) {
      data['feature'] = feature!.toJson();
    }
    data['create'] = create;
    data['view'] = view;
    data['update'] = update;
    data['delete'] = delete;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['deletedAt'] = deletedAt;
    return data;
  }
}

class AuthModelDataRole {
/*
{
  "id": "a9e564b2-a6e6-4108-bce2-2509584581bf",
  "name": "Super Admin",
  "featurePermissions": [
    {
      "id": "245f41aa-827d-4626-8bc6-1fbb3c7fde3d",
      "feature": {
        "id": "8c43b43c-65a7-4598-89eb-1e4f0d983bd8",
        "name": "EMPLOYEE_MANAGEMENT",
        "isActive": true,
        "createdAt": "2025-04-29T13:26:51.120Z",
        "updatedAt": "2025-04-29T13:26:51.120Z",
        "deletedAt": null
      },
      "create": true,
      "view": true,
      "update": true,
      "delete": true,
      "createdAt": "2025-04-29T13:26:50.797Z",
      "updatedAt": "2025-04-29T13:26:50.797Z",
      "deletedAt": null
    }
  ],
  "createdAt": "2025-04-29T13:26:51.120Z",
  "updatedAt": "2025-04-29T13:26:51.120Z",
  "deletedAt": null
}
*/

  String? id;
  String? name;
  List<AuthModelDataRoleFeaturePermissions?>? featurePermissions;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  AuthModelDataRole({
    this.id,
    this.name,
    this.featurePermissions,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  AuthModelDataRole.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    if (json['featurePermissions'] != null) {
      final v = json['featurePermissions'];
      final arr0 = <AuthModelDataRoleFeaturePermissions>[];
      v.forEach((v) {
        arr0.add(AuthModelDataRoleFeaturePermissions.fromJson(v));
      });
      featurePermissions = arr0;
    }
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    deletedAt = json['deletedAt']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    if (featurePermissions != null) {
      final v = featurePermissions;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['featurePermissions'] = arr0;
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['deletedAt'] = deletedAt;
    return data;
  }
}

class AuthModelData {
/*
{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjZTdhMjAwLTBkZDAtNGZhMC04YjZiLTI1NTAwZTY4MzI0YyIsImVtYWlsIjoiVGVsbHkuSm9obnNvbi01M2Y5NTg4Ny1lZjlkLTQ4OTQtOTcwYS00ZDcwNDcwMDNkZTJAeWFob28uY29tIiwic3RhdHVzIjoiQUNUSVZFIiwiaWF0IjoxNzQ1OTkzNjYyLCJleHAiOjE3NTQ1NDcyNjJ9.hN8e9dorl9K_el1eRpTzDfjT7dOaNmFTYNrwZbPmUB4",
  "id": "0ce7a200-0dd0-4fa0-8b6b-25500e68324c",
  "profileImg": "https://chapsandco.s3.ap-south-1.amazonaws.com/https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/34.jpg",
  "firstName": "Amely",
  "middleName": "Micah",
  "lastName": "Labadie",
  "knownAs": "Toby57-5ae24c74-b65f-4efb-848e-f5a4d96f56c2",
  "email": "Telly.Johnson-53f95887-ef9d-4894-970a-4d7047003de2@yahoo.com",
  "password": "$2b$10$ng9K7gIL80sl31loFI9bgeuJdBsI/Ki9iNsQsJA9Pabytp6XKlNVG",
  "employeeId": "962-501-3712 x892",
  "personalPhonePrefix": null,
  "personalPhoneNumber": null,
  "birthDate": "1968-02-01",
  "gender": "Female",
  "maritalStatus": "Married",
  "religion": "None",
  "nationality": "Guinea",
  "emergencyContactName": "Rafael Von",
  "emergencyPhonePrefix": "893.331.7821 x96585",
  "emergencyPhoneNumber": "zPx0GO",
  "personalPin": "(702) 265-1523",
  "workOfficePhonePrefix": "1-662-842-1685 x34689",
  "workOfficePhoneNumber": "Dustin.Raynor59@yahoo.com",
  "workOfficeMobilePrefix": "Marquardt - Koelpin",
  "workOfficeMobileNumber": "4543.03",
  "workEmail": "635.29",
  "employeeBranchName": "689.69",
  "basicSalary": "387.15",
  "homeAllowance": "123.45",
  "transportAllowance": "234.56",
  "otherAllowances": "345.67",
  "isTipEligible": true,
  "status": "ACTIVE",
  "role": {
    "id": "a9e564b2-a6e6-4108-bce2-2509584581bf",
    "name": "Super Admin",
    "featurePermissions": [
      {
        "id": "245f41aa-827d-4626-8bc6-1fbb3c7fde3d",
        "feature": {
          "id": "8c43b43c-65a7-4598-89eb-1e4f0d983bd8",
          "name": "EMPLOYEE_MANAGEMENT",
          "isActive": true,
          "createdAt": "2025-04-29T13:26:51.120Z",
          "updatedAt": "2025-04-29T13:26:51.120Z",
          "deletedAt": null
        },
        "create": true,
        "view": true,
        "update": true,
        "delete": true,
        "createdAt": "2025-04-29T13:26:50.797Z",
        "updatedAt": "2025-04-29T13:26:50.797Z",
        "deletedAt": null
      }
    ],
    "createdAt": "2025-04-29T13:26:51.120Z",
    "updatedAt": "2025-04-29T13:26:51.120Z",
    "deletedAt": null
  },
  "createdAt": "2025-04-23T20:43:05.507Z",
  "updatedAt": "2025-04-29T14:04:06.914Z",
  "deletedAt": null
}
*/

  String? accessToken;
  String? id;
  String? profileImg;
  String? firstName;
  String? middleName;
  String? lastName;
  String? knownAs;
  String? email;
  String? password;
  String? employeeId;
  String? personalPhonePrefix;
  String? personalPhoneNumber;
  String? birthDate;
  String? gender;
  String? maritalStatus;
  String? religion;
  String? nationality;
  String? emergencyContactName;
  String? emergencyPhonePrefix;
  String? emergencyPhoneNumber;
  String? personalPin;
  String? workOfficePhonePrefix;
  String? workOfficePhoneNumber;
  String? workOfficeMobilePrefix;
  String? workOfficeMobileNumber;
  String? workEmail;
  String? employeeBranchName;
  String? basicSalary;
  String? homeAllowance;
  String? transportAllowance;
  String? otherAllowances;
  bool? isTipEligible;
  String? status;
  AuthModelDataRole? role;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  AuthModelData({
    this.accessToken,
    this.id,
    this.profileImg,
    this.firstName,
    this.middleName,
    this.lastName,
    this.knownAs,
    this.email,
    this.password,
    this.employeeId,
    this.personalPhonePrefix,
    this.personalPhoneNumber,
    this.birthDate,
    this.gender,
    this.maritalStatus,
    this.religion,
    this.nationality,
    this.emergencyContactName,
    this.emergencyPhonePrefix,
    this.emergencyPhoneNumber,
    this.personalPin,
    this.workOfficePhonePrefix,
    this.workOfficePhoneNumber,
    this.workOfficeMobilePrefix,
    this.workOfficeMobileNumber,
    this.workEmail,
    this.employeeBranchName,
    this.basicSalary,
    this.homeAllowance,
    this.transportAllowance,
    this.otherAllowances,
    this.isTipEligible,
    this.status,
    this.role,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  AuthModelData.fromJson(Map<String, dynamic> json) {
    accessToken = json['accessToken']?.toString();
    id = json['id']?.toString();
    profileImg = json['profileImg']?.toString();
    firstName = json['firstName']?.toString();
    middleName = json['middleName']?.toString();
    lastName = json['lastName']?.toString();
    knownAs = json['knownAs']?.toString();
    email = json['email']?.toString();
    password = json['password']?.toString();
    employeeId = json['employeeId']?.toString();
    personalPhonePrefix = json['personalPhonePrefix']?.toString();
    personalPhoneNumber = json['personalPhoneNumber']?.toString();
    birthDate = json['birthDate']?.toString();
    gender = json['gender']?.toString();
    maritalStatus = json['maritalStatus']?.toString();
    religion = json['religion']?.toString();
    nationality = json['nationality']?.toString();
    emergencyContactName = json['emergencyContactName']?.toString();
    emergencyPhonePrefix = json['emergencyPhonePrefix']?.toString();
    emergencyPhoneNumber = json['emergencyPhoneNumber']?.toString();
    personalPin = json['personalPin']?.toString();
    workOfficePhonePrefix = json['workOfficePhonePrefix']?.toString();
    workOfficePhoneNumber = json['workOfficePhoneNumber']?.toString();
    workOfficeMobilePrefix = json['workOfficeMobilePrefix']?.toString();
    workOfficeMobileNumber = json['workOfficeMobileNumber']?.toString();
    workEmail = json['workEmail']?.toString();
    employeeBranchName = json['employeeBranchName']?.toString();
    basicSalary = json['basicSalary']?.toString();
    homeAllowance = json['homeAllowance']?.toString();
    transportAllowance = json['transportAllowance']?.toString();
    otherAllowances = json['otherAllowances']?.toString();
    isTipEligible = json['isTipEligible'];
    status = json['status']?.toString();
    role = (json['role'] != null)
        ? AuthModelDataRole.fromJson(json['role'])
        : null;
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    deletedAt = json['deletedAt']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['accessToken'] = accessToken;
    data['id'] = id;
    data['profileImg'] = profileImg;
    data['firstName'] = firstName;
    data['middleName'] = middleName;
    data['lastName'] = lastName;
    data['knownAs'] = knownAs;
    data['email'] = email;
    data['password'] = password;
    data['employeeId'] = employeeId;
    data['personalPhonePrefix'] = personalPhonePrefix;
    data['personalPhoneNumber'] = personalPhoneNumber;
    data['birthDate'] = birthDate;
    data['gender'] = gender;
    data['maritalStatus'] = maritalStatus;
    data['religion'] = religion;
    data['nationality'] = nationality;
    data['emergencyContactName'] = emergencyContactName;
    data['emergencyPhonePrefix'] = emergencyPhonePrefix;
    data['emergencyPhoneNumber'] = emergencyPhoneNumber;
    data['personalPin'] = personalPin;
    data['workOfficePhonePrefix'] = workOfficePhonePrefix;
    data['workOfficePhoneNumber'] = workOfficePhoneNumber;
    data['workOfficeMobilePrefix'] = workOfficeMobilePrefix;
    data['workOfficeMobileNumber'] = workOfficeMobileNumber;
    data['workEmail'] = workEmail;
    data['employeeBranchName'] = employeeBranchName;
    data['basicSalary'] = basicSalary;
    data['homeAllowance'] = homeAllowance;
    data['transportAllowance'] = transportAllowance;
    data['otherAllowances'] = otherAllowances;
    data['isTipEligible'] = isTipEligible;
    data['status'] = status;
    if (role != null) {
      data['role'] = role!.toJson();
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['deletedAt'] = deletedAt;
    return data;
  }
}

class AuthModel {
/*
{
  "status": true,
  "code": "SUCCESS",
  "message": "Logged in successfully.",
  "data": {
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjZTdhMjAwLTBkZDAtNGZhMC04YjZiLTI1NTAwZTY4MzI0YyIsImVtYWlsIjoiVGVsbHkuSm9obnNvbi01M2Y5NTg4Ny1lZjlkLTQ4OTQtOTcwYS00ZDcwNDcwMDNkZTJAeWFob28uY29tIiwic3RhdHVzIjoiQUNUSVZFIiwiaWF0IjoxNzQ1OTkzNjYyLCJleHAiOjE3NTQ1NDcyNjJ9.hN8e9dorl9K_el1eRpTzDfjT7dOaNmFTYNrwZbPmUB4",
    "id": "0ce7a200-0dd0-4fa0-8b6b-25500e68324c",
    "profileImg": "https://chapsandco.s3.ap-south-1.amazonaws.com/https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/34.jpg",
    "firstName": "Amely",
    "middleName": "Micah",
    "lastName": "Labadie",
    "knownAs": "Toby57-5ae24c74-b65f-4efb-848e-f5a4d96f56c2",
    "email": "Telly.Johnson-53f95887-ef9d-4894-970a-4d7047003de2@yahoo.com",
    "password": "$2b$10$ng9K7gIL80sl31loFI9bgeuJdBsI/Ki9iNsQsJA9Pabytp6XKlNVG",
    "employeeId": "962-501-3712 x892",
    "personalPhonePrefix": null,
    "personalPhoneNumber": null,
    "birthDate": "1968-02-01",
    "gender": "Female",
    "maritalStatus": "Married",
    "religion": "None",
    "nationality": "Guinea",
    "emergencyContactName": "Rafael Von",
    "emergencyPhonePrefix": "893.331.7821 x96585",
    "emergencyPhoneNumber": "zPx0GO",
    "personalPin": "(702) 265-1523",
    "workOfficePhonePrefix": "1-662-842-1685 x34689",
    "workOfficePhoneNumber": "Dustin.Raynor59@yahoo.com",
    "workOfficeMobilePrefix": "Marquardt - Koelpin",
    "workOfficeMobileNumber": "4543.03",
    "workEmail": "635.29",
    "employeeBranchName": "689.69",
    "basicSalary": "387.15",
    "homeAllowance": "123.45",
    "transportAllowance": "234.56",
    "otherAllowances": "345.67",
    "isTipEligible": true,
    "status": "ACTIVE",
    "role": {
      "id": "a9e564b2-a6e6-4108-bce2-2509584581bf",
      "name": "Super Admin",
      "featurePermissions": [
        {
          "id": "245f41aa-827d-4626-8bc6-1fbb3c7fde3d",
          "feature": {
            "id": "8c43b43c-65a7-4598-89eb-1e4f0d983bd8",
            "name": "EMPLOYEE_MANAGEMENT",
            "isActive": true,
            "createdAt": "2025-04-29T13:26:51.120Z",
            "updatedAt": "2025-04-29T13:26:51.120Z",
            "deletedAt": null
          },
          "create": true,
          "view": true,
          "update": true,
          "delete": true,
          "createdAt": "2025-04-29T13:26:50.797Z",
          "updatedAt": "2025-04-29T13:26:50.797Z",
          "deletedAt": null
        }
      ],
      "createdAt": "2025-04-29T13:26:51.120Z",
      "updatedAt": "2025-04-29T13:26:51.120Z",
      "deletedAt": null
    },
    "createdAt": "2025-04-23T20:43:05.507Z",
    "updatedAt": "2025-04-29T14:04:06.914Z",
    "deletedAt": null
  }
}
*/

  bool? status;
  String? code;
  String? message;
  AuthModelData? data;

  AuthModel({
    this.status,
    this.code,
    this.message,
    this.data,
  });

  AuthModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code']?.toString();
    message = json['message']?.toString();
    data = (json['data'] != null) ? AuthModelData.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['message'] = message;
    data['data'] = this.data!.toJson();
    return data;
  }
}
