///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChangePasswordModel {
/*
{
  "message": "Password changed successfully"
}
*/

  String? message;

  ChangePasswordModel({
    this.message,
  });
  ChangePasswordModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    return data;
  }
}
